# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-09 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipebatch',
            name='restarted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
