# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 00:43
from __future__ import unicode_literals

from django.db import migrations


def populate_ingredient_types(apps, schema_editor):
    data_list = [
        {
            'name': 'Water',
            'slug': 'water',
            'measured_by': 'volume'
        },
        {
            'name': 'Yeast',
            'slug': 'yeast',
            'measured_by': 'weight'
        },
        {
            'name': 'Hop',
            'slug': 'hop',
            'measured_by': 'weight'
        },
        {
            'name': 'Malt',
            'slug': 'malt',
            'measured_by': 'weight'
        },
        {
            'name': 'Additive',
            'slug': 'additive',
            'measured_by': None,
        }
    ]

    IngredientType = apps.get_model('ingredients', 'IngredientType')
    ingredient_types = []
    for data in data_list:
        ingredient_types.append(IngredientType(**data))

    IngredientType.objects.bulk_create(ingredient_types)


class Migration(migrations.Migration):
    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_ingredient_types),
    ]
