# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='useringredient',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Qty'),
        ),
    ]
