# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20171208_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienttype',
            name='measured_by',
            field=models.CharField(blank=True, choices=[('volume', 'volume'), ('weight', 'weight')], max_length=10, null=True),
        ),
    ]
