# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userequipment',
            name='weight_capacity',
        ),
    ]
