# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 00:41
from __future__ import unicode_literals

from django.db import migrations


def populate_equipments(apps, schema_editor):
    data_list = [
        {
            'name': 'Airlock',
            'slug': 'airlock',
            'is_measured': False
        },
        {
            'name': 'Bottle',
            'slug': 'bottle',
            'is_measured': True
        },
        {
            'name': 'Bottle Capper',
            'slug': 'bottle-capper',
            'is_measured': False
        },
        {
            'name': 'Bottle Cap',
            'slug': 'bottle-cap',
            'is_measured': False
        },
        {
            'name': 'Bottle Brush',
            'slug': 'bottle-brush',
            'is_measured': False
        },
        {
            'name': 'Fermenter',
            'slug': 'fermenter',
            'is_measured': False
        },
        {
            'name': 'Measuring Cup',
            'slug': 'measuring-cup',
            'is_measured': False
        },
        {
            'name': 'Siphon',
            'slug': 'siphon',
            'is_measured': False
        },
        {
            'name': 'Racking Cane',
            'slug': 'racking-cane',
            'is_measured': False
        },
        {
            'name': 'Bottle Filler',
            'slug': 'bottle-filler',
            'is_measured': False
        },
        {
            'name': 'Stirring Paddle',
            'slug': 'stirring-paddle',
            'is_measured': False
        },
        {
            'name': 'Thermometer',
            'slug': 'thermometer',
            'is_measured': False
        },
        {
            'name': 'Boiling Bucket',
            'slug': 'boiling-bucket',
            'is_measured': True
        },
        {
            'name': 'Hydrometer',
            'slug': 'hydrometer',
            'is_measured': False
        },
        {
            'name': 'Wine Thief',
            'slug': 'wine-thief',
            'is_measured': False
        },
        {
            'name': 'Hydrometer Jar',
            'slug': 'hydrometer-jar',
            'is_measured': False
        },
        {
            'name': 'Wort Chiller',
            'slug': 'wort-chiller',
            'is_measured': False
        },
        {
            'name': 'Strainer',
            'slug': 'strainer',
            'is_measured': False
        },
        {
            'name': 'Mash tun',
            'slug': 'mash-tun',
            'is_measured': True
        },
        {
            'name': 'Boiling Kettle',
            'slug': 'boiling-kettle',
            'is_measured': True
        },
        {
            'name': 'Hot liquor tank',
            'slug': 'hot-liquor-tank',
            'is_measured': True
        },
        {
            'name': 'Lauter tun',
            'slug': 'lauter-tun',
            'is_measured': True
        }
    ]

    Equipment = apps.get_model('equipments', 'Equipment')
    equipments = []
    for data in data_list:
        equipments.append(Equipment(**data))

    Equipment.objects.bulk_create(equipments)


class Migration(migrations.Migration):
    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_equipments),

    ]
