# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 02:06
from __future__ import unicode_literals

from django.db import migrations
import django_measurement.models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeequipment',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='recipeequipment',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='userequipment',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='userequipment',
            name='unit',
        ),
        migrations.AddField(
            model_name='userequipment',
            name='volume_capacity',
            field=django_measurement.models.MeasurementField(blank=True, measurement_class='Volume', null=True),
        ),
        migrations.AddField(
            model_name='userequipment',
            name='weight_capacity',
            field=django_measurement.models.MeasurementField(blank=True, measurement_class='Mass', null=True),
        ),
        migrations.DeleteModel(
            name='RecipeEquipment',
        ),
    ]
