# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_description'),
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('quantity', models.PositiveIntegerField(verbose_name='Qty')),
                ('capacity', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Capacity')),
                ('unit', models.CharField(choices=[('mg', 'mg'), ('g', 'gram'), ('kg', 'kilogram'), ('l', 'litre'), ('ml', 'ml')], max_length=2)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.Equipment')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
