version: '3'
services:
  brewday_db:
    image: postgres:9.6.3
    container_name: brewday_db
    environment:
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
  brewday_web:
    build: .
    container_name: brewday_web
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/brewday/
    env_file: .env
    ports:
      - "8000:8000"
    links:
      - brewday_db
    depends_on:
      - brewday_db
