# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 00:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='A short name will be used to unique identify you in the platform.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9_]+$', 32), 'Enter a valid username', 'invalid')], verbose_name='username'),
        ),
    ]
