# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 00:09
from __future__ import unicode_literals

from django.db import migrations
import src.accounts.managers


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', src.accounts.managers.CustomUserManager()),
            ],
        ),
    ]
