# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(help_text='Title of the recipe.', max_length=255, verbose_name='Title')),
                ('og', models.DecimalField(blank=True, decimal_places=4, help_text='Original Gravity', max_digits=4, null=True, verbose_name='OG')),
                ('fg', models.DecimalField(blank=True, decimal_places=4, help_text='Final Gravity', max_digits=4, null=True, verbose_name='FG')),
                ('ibu', models.PositiveIntegerField(blank=True, help_text='International Bitterness Unit', null=True, verbose_name='IBU')),
                ('srm', models.PositiveIntegerField(blank=True, help_text='Standard Reference Method', null=True, verbose_name='SRV')),
                ('abv', models.DecimalField(blank=True, decimal_places=2, help_text='Alcohool by Volume', max_digits=2, null=True, verbose_name='ABV')),
                ('steps', models.TextField(verbose_name='Steps')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(choices=[('mg', 'mg'), ('g', 'gram'), ('kg', 'kilogram'), ('l', 'litre'), ('ml', 'ml')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Unit'),
        ),
    ]
