# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('mg', 'mg'), ('g', 'gram'), ('kg', 'kilogram'), ('l', 'litre'), ('ml', 'ml')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
