# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 16:49
from __future__ import unicode_literals

from django.db import migrations
import django_measurement.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='expected_production',
        ),
        migrations.AddField(
            model_name='recipe',
            name='expected_production',
            field=django_measurement.models.MeasurementField(blank=True, measurement_class='Volume', null=True, verbose_name='Expected Production'),
        ),
    ]
