# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-03 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='expected_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Expected Production'),
            preserve_default=False,
        ),
    ]
