# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20171123_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='abv',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Alcohol by Volume', max_digits=3, null=True, verbose_name='ABV'),
        ),
    ]
