# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20171123_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='abv',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Alcohol by Volume', max_digits=4, null=True, verbose_name='ABV'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Final Gravity', max_digits=4, null=True, verbose_name='FG'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='og',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Original Gravity', max_digits=4, null=True, verbose_name='OG'),
        ),
    ]
