# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 00:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171028_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activated',
        ),
    ]
